Map<String, dynamic> getNixNutrientById(int? attrId) {
  var list = nixNutrientList.where((e) => e['attrId'] == attrId).toList();
  return (list.isEmpty) ? {} : list.first;
}

/// 响应的营养素中id对应的标签列表
List<Map<String, dynamic>> nixNutrientList = [
  {
    "attrId": 301,
    "npf2018": 1,
    "usda_tag": "CA",
    "name": "Calcium, Ca",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_calcium_mg"
  },
  {
    "attrId": 205,
    "npf2018": 1,
    "usda_tag": "CHOCDF",
    "name": "Carbohydrate, by difference",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_total_carbohydrate"
  },
  {
    "attrId": 601,
    "npf2018": 1,
    "usda_tag": "CHOLE",
    "name": "Cholesterol",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_cholesterol"
  },
  {
    "attrId": 208,
    "npf2018": 1,
    "usda_tag": "ENERC_KCAL",
    "name": "Energy",
    "unit": "kcal",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_calories"
  },
  {
    "attrId": 606,
    "npf2018": 1,
    "usda_tag": "FASAT",
    "name": "Fatty acids, total saturated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_saturated_fat"
  },
  {
    "attrId": 204,
    "npf2018": 1,
    "usda_tag": "FAT",
    "name": "Total lipid (fat)",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_total_fat"
  },
  {
    "attrId": 605,
    "npf2018": 1,
    "usda_tag": "FATRN",
    "name": "Fatty acids, total trans",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_trans_fatty_acid"
  },
  {
    "attrId": 303,
    "npf2018": 1,
    "usda_tag": "FE",
    "name": "Iron, Fe",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_iron_mg"
  },
  {
    "attrId": 291,
    "npf2018": 1,
    "usda_tag": "FIBTG",
    "name": "Fiber, total dietary",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_dietary_fiber"
  },
  {
    "attrId": 306,
    "npf2018": 1,
    "usda_tag": "K",
    "name": "Potassium, K",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_potassium"
  },
  {
    "attrId": 307,
    "npf2018": 1,
    "usda_tag": "NA",
    "name": "Sodium, Na",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_sodium"
  },
  {
    "attrId": 203,
    "npf2018": 1,
    "usda_tag": "PROCNT",
    "name": "Protein",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_protein"
  },
  {
    "attrId": 269,
    "npf2018": 1,
    "usda_tag": "SUGAR",
    "name": "Sugars, total",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_sugars"
  },
  {
    "attrId": 539,
    "npf2018": 1,
    "usda_tag": "SUGAR_ADD",
    "name": "Sugars, added",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_added_sugars"
  },
  {
    "attrId": 324,
    "npf2018": 1,
    "usda_tag": "VITD",
    "name": "Vitamin D",
    "unit": "IU",
    "naturalCommon": 1,
    "itemCpg": 1,
    "itemRestaurant": 1,
    "notes": "",
    "bulkCsField": "nf_vitamin_d_mcg"
  },
  {
    "attrId": 299,
    "npf2018": 1,
    "usda_tag": "SUGAR_ALC",
    "name": "Sugar Alcohol",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 1001,
    "npf2018": 1,
    "usda_tag": "#N/A",
    "name": "Erythritol",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 1006,
    "npf2018": 1,
    "usda_tag": "#N/A",
    "name": "Allulose",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 1002,
    "npf2018": 1,
    "usda_tag": "#N/A",
    "name": "Glycerin",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 290,
    "npf2018": 1,
    "usda_tag": "XYL",
    "name": "Xylitol",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 261,
    "npf2018": 1,
    "usda_tag": "SORB",
    "name": "Sorbitol",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 260,
    "npf2018": 1,
    "usda_tag": "MANOL",
    "name": "Mannitol",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 1003,
    "npf2018": 1,
    "usda_tag": "#N/A",
    "name": "Maltitol",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 1004,
    "npf2018": 1,
    "usda_tag": "#N/A",
    "name": "Isomalt",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 1005,
    "npf2018": 1,
    "usda_tag": "#N/A",
    "name": "Lactitol",
    "unit": "g",
    "naturalCommon": 0,
    "itemCpg": 1,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 513,
    "npf2018": 0,
    "usda_tag": "ALA_G",
    "name": "Alanine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 221,
    "npf2018": 0,
    "usda_tag": "ALC",
    "name": "Alcohol, ethyl",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 511,
    "npf2018": 0,
    "usda_tag": "ARG_G",
    "name": "Arginine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 207,
    "npf2018": 0,
    "usda_tag": "ASH",
    "name": "Ash",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 514,
    "npf2018": 0,
    "usda_tag": "ASP_G",
    "name": "Aspartic acid",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 454,
    "npf2018": 0,
    "usda_tag": "BETN",
    "name": "Betaine",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 262,
    "npf2018": 0,
    "usda_tag": "CAFFN",
    "name": "Caffeine",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 639,
    "npf2018": 0,
    "usda_tag": "CAMD5",
    "name": "Campesterol",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 322,
    "npf2018": 0,
    "usda_tag": "CARTA",
    "name": "Carotene, alpha",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 321,
    "npf2018": 0,
    "usda_tag": "CARTB",
    "name": "Carotene, beta",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 326,
    "npf2018": 0,
    "usda_tag": "CHOCAL",
    "name": "Vitamin D3 (cholecalciferol)",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 421,
    "npf2018": 0,
    "usda_tag": "CHOLN",
    "name": "Choline, total",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 334,
    "npf2018": 0,
    "usda_tag": "CRYPX",
    "name": "Cryptoxanthin, beta",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 312,
    "npf2018": 0,
    "usda_tag": "CU",
    "name": "Copper, Cu",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 507,
    "npf2018": 0,
    "usda_tag": "CYS_G",
    "name": "Cystine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 268,
    "npf2018": 0,
    "usda_tag": "ENERC_KJ",
    "name": "Energy",
    "unit": "kJ",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 325,
    "npf2018": 0,
    "usda_tag": "ERGCAL",
    "name": "Vitamin D2 (ergocalciferol)",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 610,
    "npf2018": 0,
    "usda_tag": "F10D0",
    "name": "10:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 611,
    "npf2018": 0,
    "usda_tag": "F12D0",
    "name": "12:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 696,
    "npf2018": 0,
    "usda_tag": "F13D0",
    "name": "13:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 612,
    "npf2018": 0,
    "usda_tag": "F14D0",
    "name": "14:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 625,
    "npf2018": 0,
    "usda_tag": "F14D1",
    "name": "14:01",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 652,
    "npf2018": 0,
    "usda_tag": "F15D0",
    "name": "15:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 697,
    "npf2018": 0,
    "usda_tag": "F15D1",
    "name": "15:01",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 613,
    "npf2018": 0,
    "usda_tag": "F16D0",
    "name": "16:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 626,
    "npf2018": 0,
    "usda_tag": "F16D1",
    "name": "16:1 undifferentiated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 673,
    "npf2018": 0,
    "usda_tag": "F16D1C",
    "name": "16:1 c",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 662,
    "npf2018": 0,
    "usda_tag": "F16D1T",
    "name": "16:1 t",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 653,
    "npf2018": 0,
    "usda_tag": "F17D0",
    "name": "17:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 687,
    "npf2018": 0,
    "usda_tag": "F17D1",
    "name": "17:01",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 614,
    "npf2018": 0,
    "usda_tag": "F18D0",
    "name": "18:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 617,
    "npf2018": 0,
    "usda_tag": "F18D1",
    "name": "18:1 undifferentiated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 674,
    "npf2018": 0,
    "usda_tag": "F18D1C",
    "name": "18:1 c",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 663,
    "npf2018": 0,
    "usda_tag": "F18D1T",
    "name": "18:1 t",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 859,
    "npf2018": 0,
    "usda_tag": "F18D1TN7",
    "name": "18:1-11t (18:1t n-7)",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 618,
    "npf2018": 0,
    "usda_tag": "F18D2",
    "name": "18:2 undifferentiated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 670,
    "npf2018": 0,
    "usda_tag": "F18D2CLA",
    "name": "18:2 CLAs",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 675,
    "npf2018": 0,
    "usda_tag": "F18D2CN6",
    "name": "18:2 n-6 c,c",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 669,
    "npf2018": 0,
    "usda_tag": "F18D2TT",
    "name": "18:2 t,t",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 619,
    "npf2018": 0,
    "usda_tag": "F18D3",
    "name": "18:3 undifferentiated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 851,
    "npf2018": 0,
    "usda_tag": "F18D3CN3",
    "name": "18:3 n-3 c,c,c (ALA)",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 685,
    "npf2018": 0,
    "usda_tag": "F18D3CN6",
    "name": "18:3 n-6 c,c,c",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 627,
    "npf2018": 0,
    "usda_tag": "F18D4",
    "name": "18:04",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 615,
    "npf2018": 0,
    "usda_tag": "F20D0",
    "name": "20:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 628,
    "npf2018": 0,
    "usda_tag": "F20D1",
    "name": "20:01",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 672,
    "npf2018": 0,
    "usda_tag": "F20D2CN6",
    "name": "20:2 n-6 c,c",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 689,
    "npf2018": 0,
    "usda_tag": "F20D3",
    "name": "20:3 undifferentiated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 852,
    "npf2018": 0,
    "usda_tag": "F20D3N3",
    "name": "20:3 n-3",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 853,
    "npf2018": 0,
    "usda_tag": "F20D3N6",
    "name": "20:3 n-6",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 620,
    "npf2018": 0,
    "usda_tag": "F20D4",
    "name": "20:4 undifferentiated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 855,
    "npf2018": 0,
    "usda_tag": "F20D4N6",
    "name": "20:4 n-6",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 629,
    "npf2018": 0,
    "usda_tag": "F20D5",
    "name": "20:5 n-3 (EPA)",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 857,
    "npf2018": 0,
    "usda_tag": "F21D5",
    "name": "21:05",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 624,
    "npf2018": 0,
    "usda_tag": "F22D0",
    "name": "22:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 630,
    "npf2018": 0,
    "usda_tag": "F22D1",
    "name": "22:1 undifferentiated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 858,
    "npf2018": 0,
    "usda_tag": "F22D4",
    "name": "22:04",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 631,
    "npf2018": 0,
    "usda_tag": "F22D5",
    "name": "22:5 n-3 (DPA)",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 621,
    "npf2018": 0,
    "usda_tag": "F22D6",
    "name": "22:6 n-3 (DHA)",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 654,
    "npf2018": 0,
    "usda_tag": "F24D0",
    "name": "24:00:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 671,
    "npf2018": 0,
    "usda_tag": "F24D1C",
    "name": "24:1 c",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 607,
    "npf2018": 0,
    "usda_tag": "F4D0",
    "name": "4:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 608,
    "npf2018": 0,
    "usda_tag": "F6D0",
    "name": "6:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 609,
    "npf2018": 0,
    "usda_tag": "F8D0",
    "name": "8:00",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 645,
    "npf2018": 0,
    "usda_tag": "FAMS",
    "name": "Fatty acids, total monounsaturated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 646,
    "npf2018": 0,
    "usda_tag": "FAPU",
    "name": "Fatty acids, total polyunsaturated",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 693,
    "npf2018": 0,
    "usda_tag": "FATRNM",
    "name": "Fatty acids, total trans-monoenoic",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 695,
    "npf2018": 0,
    "usda_tag": "FATRNP",
    "name": "Fatty acids, total trans-polyenoic",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 313,
    "npf2018": 0,
    "usda_tag": "FLD",
    "name": "Fluoride, F",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 417,
    "npf2018": 0,
    "usda_tag": "FOL",
    "name": "Folate, total",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 431,
    "npf2018": 0,
    "usda_tag": "FOLAC",
    "name": "Folic acid",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 435,
    "npf2018": 0,
    "usda_tag": "FOLDFE",
    "name": "Folate, DFE",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 432,
    "npf2018": 0,
    "usda_tag": "FOLFD",
    "name": "Folate, food",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 212,
    "npf2018": 0,
    "usda_tag": "FRUS",
    "name": "Fructose",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 287,
    "npf2018": 0,
    "usda_tag": "GALS",
    "name": "Galactose",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 515,
    "npf2018": 0,
    "usda_tag": "GLU_G",
    "name": "Glutamic acid",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 211,
    "npf2018": 0,
    "usda_tag": "GLUS",
    "name": "Glucose (dextrose)",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 516,
    "npf2018": 0,
    "usda_tag": "GLY_G",
    "name": "Glycine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 512,
    "npf2018": 0,
    "usda_tag": "HISTN_G",
    "name": "Histidine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 521,
    "npf2018": 0,
    "usda_tag": "HYP",
    "name": "Hydroxyproline",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 503,
    "npf2018": 0,
    "usda_tag": "ILE_G",
    "name": "Isoleucine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 213,
    "npf2018": 0,
    "usda_tag": "LACS",
    "name": "Lactose",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 504,
    "npf2018": 0,
    "usda_tag": "LEU_G",
    "name": "Leucine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 338,
    "npf2018": 0,
    "usda_tag": "LUT+ZEA",
    "name": "Lutein + zeaxanthin",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 337,
    "npf2018": 0,
    "usda_tag": "LYCPN",
    "name": "Lycopene",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 505,
    "npf2018": 0,
    "usda_tag": "LYS_G",
    "name": "Lysine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 214,
    "npf2018": 0,
    "usda_tag": "MALS",
    "name": "Maltose",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 506,
    "npf2018": 0,
    "usda_tag": "MET_G",
    "name": "Methionine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 304,
    "npf2018": 0,
    "usda_tag": "MG",
    "name": "Magnesium, Mg",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 428,
    "npf2018": 0,
    "usda_tag": "MK4",
    "name": "Menaquinone-4",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 315,
    "npf2018": 0,
    "usda_tag": "MN",
    "name": "Manganese, Mn",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 406,
    "npf2018": 0,
    "usda_tag": "NIA",
    "name": "Niacin",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 573,
    "npf2018": 0,
    "usda_tag": "NULL",
    "name": "Vitamin E, added",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 578,
    "npf2018": 0,
    "usda_tag": "NULL",
    "name": "Vitamin B-12, added",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 257,
    "npf2018": 0,
    "usda_tag": "NULL",
    "name": "Adjusted Protein",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 664,
    "npf2018": 0,
    "usda_tag": "NULL",
    "name": "22:1 t",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 676,
    "npf2018": 0,
    "usda_tag": "NULL",
    "name": "22:1 c",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 856,
    "npf2018": 0,
    "usda_tag": "NULL",
    "name": "18:3i",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 665,
    "npf2018": 0,
    "usda_tag": "NULL",
    "name": "18:2 t not further defined",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 666,
    "npf2018": 0,
    "usda_tag": "NULL",
    "name": "18:2 i",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 305,
    "npf2018": 0,
    "usda_tag": "P",
    "name": "Phosphorus, P",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 410,
    "npf2018": 0,
    "usda_tag": "PANTAC",
    "name": "Pantothenic acid",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 508,
    "npf2018": 0,
    "usda_tag": "PHE_G",
    "name": "Phenylalanine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 636,
    "npf2018": 0,
    "usda_tag": "PHYSTR",
    "name": "Phytosterols",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 517,
    "npf2018": 0,
    "usda_tag": "PRO_G",
    "name": "Proline",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 319,
    "npf2018": 0,
    "usda_tag": "RETOL",
    "name": "Retinol",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 405,
    "npf2018": 0,
    "usda_tag": "RIBF",
    "name": "Riboflavin",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 317,
    "npf2018": 0,
    "usda_tag": "SE",
    "name": "Selenium, Se",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 518,
    "npf2018": 0,
    "usda_tag": "SER_G",
    "name": "Serine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 641,
    "npf2018": 0,
    "usda_tag": "SITSTR",
    "name": "Beta-sitosterol",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 209,
    "npf2018": 0,
    "usda_tag": "STARCH",
    "name": "Starch",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 638,
    "npf2018": 0,
    "usda_tag": "STID7",
    "name": "Stigmasterol",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 210,
    "npf2018": 0,
    "usda_tag": "SUCS",
    "name": "Sucrose",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 263,
    "npf2018": 0,
    "usda_tag": "THEBRN",
    "name": "Theobromine",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 404,
    "npf2018": 0,
    "usda_tag": "THIA",
    "name": "Thiamin",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 502,
    "npf2018": 0,
    "usda_tag": "THR_G",
    "name": "Threonine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 323,
    "npf2018": 0,
    "usda_tag": "TOCPHA",
    "name": "Vitamin E (alpha-tocopherol)",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 341,
    "npf2018": 0,
    "usda_tag": "TOCPHB",
    "name": "Tocopherol, beta",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 343,
    "npf2018": 0,
    "usda_tag": "TOCPHD",
    "name": "Tocopherol, delta",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 342,
    "npf2018": 0,
    "usda_tag": "TOCPHG",
    "name": "Tocopherol, gamma",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 501,
    "npf2018": 0,
    "usda_tag": "TRP_G",
    "name": "Tryptophan",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 509,
    "npf2018": 0,
    "usda_tag": "TYR_G",
    "name": "Tyrosine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 510,
    "npf2018": 0,
    "usda_tag": "VAL_G",
    "name": "Valine",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 318,
    "npf2018": 0,
    "usda_tag": "VITA_IU",
    "name": "Vitamin A, IU",
    "unit": "IU",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 320,
    "npf2018": 0,
    "usda_tag": "VITA_RAE",
    "name": "Vitamin A, RAE",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 418,
    "npf2018": 0,
    "usda_tag": "VITB12",
    "name": "Vitamin B-12",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 415,
    "npf2018": 0,
    "usda_tag": "VITB6A",
    "name": "Vitamin B-6",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 401,
    "npf2018": 0,
    "usda_tag": "VITC",
    "name": "Vitamin C, total ascorbic acid",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 328,
    "npf2018": 0,
    "usda_tag": "VITD",
    "name": "Vitamin D (D2 + D3)",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 430,
    "npf2018": 0,
    "usda_tag": "VITK1",
    "name": "Vitamin K (phylloquinone)",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 429,
    "npf2018": 0,
    "usda_tag": "VITK1D",
    "name": "Dihydrophylloquinone",
    "unit": "Âµg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 255,
    "npf2018": 0,
    "usda_tag": "WATER",
    "name": "Water",
    "unit": "g",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 309,
    "npf2018": 0,
    "usda_tag": "ZN",
    "name": "Zinc, Zn",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 344,
    "npf2018": "",
    "usda_tag": "TOCTRA",
    "name": "Tocotrienol, alpha",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 345,
    "npf2018": "",
    "usda_tag": "TOCTRB",
    "name": "Tocotrienol, beta",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 346,
    "npf2018": "",
    "usda_tag": "TOCTRG",
    "name": "Tocotrienol, gamma",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  },
  {
    "attrId": 347,
    "npf2018": "",
    "usda_tag": "TOCTRD",
    "name": "Tocotrienol,delta",
    "unit": "mg",
    "naturalCommon": 1,
    "itemCpg": 0,
    "itemRestaurant": 0,
    "notes": "",
    "bulkCsField": ""
  }
];
